service: uipath-webhook-receiver

provider:
  name: aws
  runtime: python2.7
  region: ap-northeast-1
  environment:
    orchestrator_url: ${file(config.json):orchestrator_url}
    tenancy_name: ${file(config.json):orchestrator_tenancy_name}
    username: ${file(config.json):orchestrator_username}
    password: ${file(config.json):orchestrator_password}
    api_key: ${file(config.$son):orchestrator_api_key}
    queue_name: ${file(config.json):queue_name}
    process_name: ${file(config.json):process_name}

plugins:
  - serverless-python-requirements

functions:
  backlog:
    handler: handler.backlog_handler
  iot_button:
    handler: handler.iot_button_handler

