service: uipath-webhook-receiver

provider:
  name: aws
  runtime: python2.7
  region: ap-northeast-1
  environment:
    orchestrator_url: ${file(config.json):orchestrator_url}
    orchestrator_tenancy_name: ${file(config.json):orchestrator_tenancy_name}
    orchestrator_username: ${file(config.json):orchestrator_username}
    orchestrator_password: ${file(config.json):orchestrator_password}
    orchestrator_api_key: ${file(config.$son):orchestrator_api_key}
    orchestrator_queue_name: ${file(config.json):orchestrator_queue_name}
    backlog_process_name: ${file(config.json):backlog_process_name}
    hangout_webhook_url: ${file(config.json):hangout_webhook_url}
    slack_token: ${file(config.json):slack_token}


plugins:
  - serverless-python-requirements

functions:
  backlog:
    handler: handler.backlog_handler
    events:
      - http:
          path: uipath-webhook-receiver/backlog
          method: post

  hagout_chat:
    handler: handler.hagout_chat_handler
    events:
      - http:
          path: uipath-webhook-receiver/hagout_chat
          method: post

  http:
    handler: handler.http_handler
    events:
      - http:
          path: uipath-webhook-receiver/http
          method: post

  iot_button:
    handler: handler.iot_button_handler

  slack:
    handler: handler.slash_command_handler
    events:
      - http:
          path: uipath-webhook-receiver/slash_command
          method: post
