service: uipath-webhook-receiver

provider:
  name: aws
  runtime: python2.7
  region: ap-northeast-1
  environment:
    language: ${file(config.json):language}
    orchestrator_url: ${file(config.json):orchestrator.url}
    orchestrator_tenancy_name: ${file(config.json):orchestrator.tenancy_name}
    orchestrator_username: ${file(config.json):orchestrator.username}
    orchestrator_password: ${file(config.json):orchestrator.password}
    orchestrator_api_key: ${file(config.$son):orchestrator.api_key}
    orchestrator_queue_name: ${file(config.json):orchestrator.queue_name}

plugins:
  - serverless-python-requirements

functions:
  backlog:
    handler: handler.backlog_handler
    environment:
      process_name: ${file(config.json):backlog.process_name}
    events:
      - http:
          path: uipath-webhook-receiver/backlog
          method: post

  github:
    handler: handler.github_handler
    environment:
      secret: ${file(config.json):github.secret}
      process_name: ${file(config.json):github.process_name}
    events:
      - http:
          path: uipath-webhook-receiver/github
          method: post
  
  hagout_chat:
    handler: handler.hagout_chat_handler
    environment:
      available_processes: ${file(config.json):hangout.available_processes}
      token: ${file(config.json):hangout.verification_token}
    events:
      - http:
          path: uipath-webhook-receiver/hagout_chat
          method: post

  http:
    handler: handler.http_handler
    environment:
      available_processes: ${file(config.json):http.available_processes}
    events:
      - http:
          path: uipath-webhook-receiver/http
          method: get
      - http:
          path: uipath-webhook-receiver/http
          method: post

  iot_button:
    handler: handler.iot_button_handler

  slack:
    handler: handler.slash_command_handler
    environment:
      verification_token: ${file(config.json):slack.verification_token}
      available_processes: ${file(config.json):slack.available_processes}
    events:
      - http:
          path: uipath-webhook-receiver/slash_command
          method: post
